In [36]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import geopandas as gpd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('display.max_columns', None)

In [11]:
ghg2013 = pd.read_csv('ghg2013.csv')

In [3]:
ghg2018 = pd.read_csv('ghg2018.csv')

In [19]:
print('ghg2013 has '+ str(len(ghg2013)) + " records")
print('ghg2018 has '+ str(len(ghg2018)) + " records")

ghg2013 has 16170 records
ghg2018 has 25939 records

In [46]:
###  join by BIN
ghg2013_join = pd.DataFrame(columns=['BIN','GHG'])
ghg2013_join['BIN'] = ghg2013['BIN'].str.replace(',','')
ghg2013_join['GHG'] = ghg2013['Total GHG Emissions(MtCO2e)']
join_BIN = pd.merge(ghg2013_join, ghg2018, left_on="BIN", right_on="NYC Building Identification Number (BIN)")
#join_BIN
print("join by BIN has "+str(len(join_BIN[join_BIN[['GHG','Total GHG Emissions (Metric Tons CO2e)']].notnull().all(1)]))+" records")

join by BIN has 8042 records

In [88]:
ghg2013.head(3)

,Record Number,BBL,Co-reported BBL Status,BBLs Co-reported,Reported NYC Building Identificaiton Numbers (BINs),Street Number,Street Name,Borough,Postcode,DOF Benchmarking Submission Status,Site EUI(kBtu/ft2),Weather Normalized Site EUI(kBtu/ft2),Source EUI(kBtu/ft2),Weather Normalized Source EUI(kBtu/ft2),Municipally Supplied Potable Water - Indoor Intensity (gal/ft²),Automatic Water Benchmarking Eligible,Reported Water Method,ENERGY STAR Score,Total GHG Emissions(MtCO2e),Direct GHG Emissions(MtCO2e),Indirect GHG Emissions(MtCO2e),Reported Property Floor Area (Building(s)) (ft²),DOF Property Floor Area (Buildngs and Parking)(ft2),Primary Property Type - Self Selected,DOF Number of Buildings,Latitude,Longitude,Community Board,Council District,Census Tract,BIN,NTA
0,12086,1.000410e+09,NaN,1000410001,1001007,NaN,NaN,Manhattan,NaN,BBL not valid,NaN,Not Available,NaN,Not Available,Not Available,NaN,NaN,Not Available,NaN,NaN,NaN,918919,NaN,Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14354,4.021460e+09,NaN,NaN,NaN,63-10,108 STREET,Queens,11375.0,No Submission Matched to BBL,NaN,NaN,NaN,NaN,NaN,Yes,None,NaN,NaN,NaN,NaN,NaN,"82,730",NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,12150,2.027620e+09,NaN,2027620097,2006460,NaN,NaN,Bronx,NaN,BBL not valid,NaN,Not Available,NaN,Not Available,Not Available,NaN,NaN,Not Available,NaN,NaN,NaN,64200,NaN,Multifamily Housing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
### join by BBL
ghg2013_join = pd.DataFrame(columns=['BBL','GHG'])
ghg2013_join['BBL'] = ghg2013['BBL'].astype(str).str[:-2]
ghg2013_join['GHG'] = ghg2013['Total GHG Emissions(MtCO2e)']
join_BBL = pd.merge(ghg2013_join, ghg2018, left_on="BBL", right_on="BBL - 10 digits")
print("join by BBL has "+str(len(join_BBL[join_BIN[['GHG','Total GHG Emissions (Metric Tons CO2e)']].notnull().all(1)]))+" records")

join by BBL has 13748 records

In [64]:
ghg_merge = join_BBL[join_BIN[['GHG','Total GHG Emissions (Metric Tons CO2e)']].notnull().all(1)]

In [65]:
ghg_merge.head(3)

,BBL,GHG,Order,Property Id,Property Name,Parent Property Id,Parent Property Name,City Building,BBL - 10 digits,"NYC Borough, Block and Lot (BBL) self - reported",NYC Building Identification Number (BIN),Address 1 (self - reported),Address 2 (self - reported),Postcode,Street Number,Street Name,Borough,DOF Gross Floor Area (ft²),Self-Reported Gross Floor Area (ft²),Primary Property Type - Self Selected,List of All Property Use Types at Property,Largest Property Use Type,Largest Property Use Type - Gross Floor Area (ft²),2nd Largest Property Use Type,2nd Largest Property Use - Gross Floor Area (ft²),3rd Largest Property Use Type,3rd Largest Property Use Type - Gross Floor Area (ft²),Year Built,Number of Buildings,Occupancy,Metered Areas (Energy),Metered Areas (Water),ENERGY STAR Score,Source EUI (kBtu/ft²),Weather Normalized Source EUI (kBtu/ft²),Site EUI (kBtu/ft²),Weather Normalized Site EUI (kBtu/ft²),Weather Normalized Site Electricity Intensity (kWh/ft²),Weather Normalized Site Natural Gas Intensity (therms/ft²),Fuel Oil #1 Use (kBtu),Fuel Oil #2 Use (kBtu),Fuel Oil #4 Use (kBtu),Fuel Oil #5 & 6 Use (kBtu),Diesel #2 Use (kBtu),Kerosene Use (kBtu),Propane Use (kBtu),District Steam Use (kBtu),District Hot Water Use (kBtu),District Chilled Water Use (kBtu),Natural Gas Use (kBtu),Weather Normalized Site Natural Gas Use (therms),Electricity Use - Grid Purchase (kBtu),Electricity Use - Grid Purchase (kWh),Weather Normalized Site Electricity (kWh),Annual Maximum Demand (kW),Annual Maximum Demand (MM/YYYY),Total GHG Emissions (Metric Tons CO2e),Direct GHG Emissions (Metric Tons CO2e),Indirect GHG Emissions (Metric Tons CO2e),Water Use (All Water Sources) (kgal),Water Use Intensity (All Water Sources) (gal/ft²),Water Required?,Generation Date,Latitude,Longitude,Community Board,Council District,Census Tract,NTA
8,3087210375,1297.8,"12,262",5806484,1311 Brightwater Avenue - 43878,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,3087210375,3-08721-0375,3245726,1311 Brightwater Avenue,Not Available,11235.0,1311,Brightwater Avenue,Brooklyn,NaN,"289,000",Multifamily Housing,Multifamily Housing,Multifamily Housing,"289,000",Not Available,Not Available,Not Available,Not Available,"1,959",1,100,Whole Building,Not Available,87,85.2,85.4,68,68.1,2.3,0.6,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,1.73522737E7,173834.7,2286956.5,670268.5,671631.7,Not Available,Not Available,1115.3,921.7,193.7,Not Available,Not Available,NaN,04/10/2019 03:31:01 PM,40.575682,-73.955388,313.0,48.0,"61,002",Brighton Beach
10,3008640001,1032.7,"17,686",6351949,526 59 Street,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,3008640001,3-00864-0001,3337343,5901 6th Avenue,Not Available,11220.0,5901,6th Avenue,Brooklyn,"353,342","52,990",Worship Facility,Worship Facility,Worship Facility,"52,990",Not Available,Not Available,Not Available,Not Available,"1,931",1,100,Whole Building,Not Available,1,236.1,Not Available,232.2,Not Available,Not Available,0.1,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,354507.1,3545.1,Not Available,Not Available,Not Available,Not Available,Not Available,918.9,915.5,Not Available,Not Available,Not Available,No,04/30/2019 06:58:43 PM,40.638642,-74.013440,307.0,38.0,102,Sunset Park East
14,1013110040,3556.4,"25,238",7441525,950 Third Avenue,Not Applicable: Standalone Property,Not Applicable: Standalone Property,No,1013110040,1-01311-0040,1036882,950 Third Avenue,Not Available,10022.0,950,Third Avenue,Manhattan,"313,200","320,585",Office,"Office, Retail Store",Office,"309,190",Retail Store,11395,Not Available,Not Available,"1,977",1,100,Whole Building,Not Available,50,237.3,229.5,136.1,130.3,13.4,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,2.88803766E7,Not Available,Not Available,Not Available,Not Available,14759775,4325842.1,4281091.5,Not Available,Not Available,3167.6,0,3167.6,Not Available,Not Available,No,07/26/2019 09:41:50 AM,40.760132,-73.967542,106.0,4.0,"11,203",Turtle Bay-East Midtown

In [71]:
ghg_merge['Total GHG Emissions (Metric Tons CO2e)'] = pd.to_numeric(ghg_merge['Total GHG Emissions (Metric Tons CO2e)'],errors='coerce')
ghg_merge['GHG'] = pd.to_numeric(ghg_merge['GHG'],errors='coerce')

In [72]:
ghg_merge['GHG change'] = (ghg_merge['Total GHG Emissions (Metric Tons CO2e)']-ghg_merge['GHG'])/ghg_merge['GHG']

In [76]:
ghg_merge = ghg_merge[['BBL','GHG change','Borough','Self-Reported Gross Floor Area (ft²)',
                       'Largest Property Use Type','Year Built','ENERGY STAR Score','Occupancy','Census Tract']]

In [77]:
ghg_merge.to_csv('ghg.csv')

In [78]:
### merge with pluto data
pluto = pd.read_csv('pluto.csv')
pluto.head(3)

,borough,block,lot,cd,ct2010,cb2010,schooldist,council,zipcode,firecomp,policeprct,healtharea,sanitboro,sanitsub,address,zonedist1,zonedist2,zonedist3,zonedist4,overlay1,overlay2,spdist1,spdist2,spdist3,ltdheight,splitzone,bldgclass,landuse,easements,ownertype,ownername,lotarea,bldgarea,comarea,resarea,officearea,retailarea,garagearea,strgearea,factryarea,otherarea,areasource,numbldgs,numfloors,unitsres,unitstotal,lotfront,lotdepth,bldgfront,bldgdepth,ext,proxcode,irrlotcode,lottype,bsmtcode,assessland,assesstot,exempttot,yearbuilt,yearalter1,yearalter2,histdist,landmark,builtfar,residfar,commfar,facilfar,borocode,bbl,condono,tract2010,xcoord,ycoord,latitude,longitude,zonemap,zmcode,sanborn,taxmap,edesignum,appbbl,appdate,plutomapid,version,sanitdistrict,healthcenterdistrict,firm07_flag,pfirm15_flag,rpaddate,dcasdate,zoningdate,landmkdate,basempdate,masdate,polidate,edesigdate,geom,dcpedited,notes
0,BK,834,46,307.0,106.0,2001.0,20.0,38.0,11220.0,L114,72.0,6700.0,3.0,4E,5524 8 AVENUE,R6,NaN,NaN,NaN,C2-4,NaN,NaN,NaN,NaN,NaN,N,S9,4.0,0.0,NaN,"RUTUELO FAMILY TRUST, DATED AUGUST 14, 2 014",1613.0,3648.0,1050.0,2598.0,0.0,1050.0,0.0,0.0,0.0,0.0,2.0,1.0,3.00,2.0,4.0,20.17,80.0,20.17,52.0,E,0.0,N,3.0,5.0,146250.0,350550.0,0.0,1931.0,0.0,0.0,NaN,NaN,2.26,2.43,0.0,4.8,3,3008340046,NaN,106.0,982211.0,171707.0,40.637972,-74.007347,22a,NaN,306A034,30307.0,NaN,NaN,NaN,1,20v1,7.0,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0106000020E61000000100000001030000000100000005...,NaN,NaN
1,QN,4042,106,407.0,929.0,3000.0,25.0,19.0,11356.0,E297,109.0,210.0,4.0,5D,13-10 COLLEGE POINT BLVD,R2A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,A1,1.0,0.0,NaN,"MOY, WAYNE",5000.0,3276.0,0.0,3276.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.75,1.0,1.0,50.00,100.0,26.00,35.0,EG,1.0,N,5.0,2.0,12240.0,78900.0,1400.0,1910.0,0.0,0.0,NaN,NaN,0.66,0.50,0.0,1.0,4,4040420106,NaN,929.0,1026895.0,225880.0,40.786562,-73.846003,7b,NaN,405 034,42103.0,NaN,NaN,NaN,1,20v1,7.0,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0106000020E61000000100000001030000000100000007...,NaN,NaN
2,BK,4679,17,317.0,866.0,3002.0,18.0,41.0,11203.0,L174,67.0,5510.0,3.0,3C,230 EAST 54 STREET,R5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,B1,1.0,0.0,NaN,DONNA SMITH JORDON,3000.0,2814.0,0.0,2814.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.00,2.0,2.0,30.00,100.0,20.50,67.0,G,1.0,N,5.0,2.0,18120.0,34380.0,1400.0,1920.0,0.0,0.0,NaN,NaN,0.94,1.25,0.0,2.0,3,3046790017,NaN,866.0,1004527.0,177269.0,40.653216,-73.926923,17b,NaN,310 060,31502.0,NaN,NaN,NaN,1,20v1,17.0,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0106000020E61000000100000001030000000100000006...,NaN,NaN

In [79]:
pluto.columns

Index(['borough', 'block', 'lot', 'cd', 'ct2010', 'cb2010', 'schooldist',
       'council', 'zipcode', 'firecomp', 'policeprct', 'healtharea',
       'sanitboro', 'sanitsub', 'address', 'zonedist1', 'zonedist2',
       'zonedist3', 'zonedist4', 'overlay1', 'overlay2', 'spdist1', 'spdist2',
       'spdist3', 'ltdheight', 'splitzone', 'bldgclass', 'landuse',
       'easements', 'ownertype', 'ownername', 'lotarea', 'bldgarea', 'comarea',
       'resarea', 'officearea', 'retailarea', 'garagearea', 'strgearea',
       'factryarea', 'otherarea', 'areasource', 'numbldgs', 'numfloors',
       'unitsres', 'unitstotal', 'lotfront', 'lotdepth', 'bldgfront',
       'bldgdepth', 'ext', 'proxcode', 'irrlotcode', 'lottype', 'bsmtcode',
       'assessland', 'assesstot', 'exempttot', 'yearbuilt', 'yearalter1',
       'yearalter2', 'histdist', 'landmark', 'builtfar', 'residfar', 'commfar',
       'facilfar', 'borocode', 'bbl', 'condono', 'tract2010', 'xcoord',
       'ycoord', 'latitude', 'longitude', 'zonemap', 'zmcode', 'sanborn',
       'taxmap', 'edesignum', 'appbbl', 'appdate', 'plutomapid', 'version',
       'sanitdistrict', 'healthcenterdistrict', 'firm07_flag', 'pfirm15_flag',
       'rpaddate', 'dcasdate', 'zoningdate', 'landmkdate', 'basempdate',
       'masdate', 'polidate', 'edesigdate', 'geom', 'dcpedited', 'notes'],
      dtype='object')

In [80]:
pluto = pluto[['bbl','latitude', 'longitude','borough','ct2010','bldgclass','landuse','bldgarea','numfloors',
              'comarea','resarea', 'officearea', 'retailarea', 'garagearea', 'strgearea','factryarea',
              'assessland', 'assesstot','builtfar',]]

In [84]:
pluto['bbl'] = pluto['bbl'].astype(str)

In [85]:
ghg_pluto = pd.merge(ghg_merge, pluto, left_on="BBL", right_on="bbl")

In [87]:
ghg_pluto.to_csv('ghg_pluto.csv')